### ISSUE TITLE
Dropdown container position

### ISSUE THREAD

**Issue by martonaron** [Lorenzobettega/simplesearchdropdown#5] opened 2023-09-06 09:34 UTC
When I click on the widget and it opens the dropdown area, it opens the keyboard too, but the area doesn't move with the keyboard and will be behind that. If I click two more times on the widget it closes and opens the dropdown area so it will be visible because the keyboard is already open, and if I start writing it will be visible too, but it's not user-friendly. I'd be happy if you could solve that to move with keyboard automatically.

**Comment by Macacoazul01** [comment] 2023-09-15 01:42
can you send some prints and a sample code?

**Comment by Lorenzobettega** [comment] 2023-09-20 21:51
> can you send some prints and a sample code?

@martonaron this will help us to fix this issue

**Comment by Macacoazul01** [comment] 2023-10-04 16:46
@martonaron i reproduced the issue here. We wasn't seeing it because our project uses the package on desktop mode so the keyboard poping up isnt a problem.
A way to "fix" it could be listening to the keyboard status and changing the overlay position with it, but the package we were pretending to use needs to fix this issue first:
https://github.com/MisterJimson/flutter_keyboard_visibility/issues/137

**Comment by Lorenzobettega** [comment] 2023-10-06 19:59
Fixed on 2.2.0
We decided to not use flutter_keyboard_visibility

**Closed by Lorenzobettega** 2023-10-06 19:59 UTC
